### ISSUE TITLE
error | uncaughtException: Cannot access 'outputPath' before initialization

### ISSUE THREAD

**Issue by ant066** [403-html/mochawesome-json-to-md#39]
error | uncaughtException: Cannot access 'outputPath' before initialization

**Comment by philippjenni** [comment]
its works withs version 1.0.1 and breaks from version 1.1.0

**Comment by 403-html** [comment]
Hi ant066! Thanks for opening this issue. I'm looking into this right now. I'll come back to this when I'll know a bit more, because between 1.0.1 and 1.1.0 I just added support for better logging.

**Comment by 403-html** [comment]
Thank you for pointing this out. Upon closer inspection, I noticed the issue in the following snippet:

```javascript
  logger.info(`Creating directory structure: ${outputPath}`);
  const outputPath = pathPkg.dirname(output);
  fs.mkdirSync(outputPath, { recursive: true });
```

It appears that the logger.info call is being made before the outputPath constant is defined. I'm preparing a pull request to correct this mistake. Appreciate your attention to this detail, @ant066.

**Comment by 403-html** [comment]
New version has been published to NPM: [https://www.npmjs.com/package/mochawesome-json-to-md/v/1.2.1](https://www.npmjs.com/package/mochawesome-json-to-md/v/1.2.1)

Feel free to update package in place where you use it.
