### ISSUE TITLE
Duration is wrong

### ISSUE THREAD

**Issue by froebisch-infai** [403-html/mochawesome-json-to-md#9]
The formula in index.js line 102 is wrong
 const genDuration = showDuration
    ? `> Duration: ${Math.round(duration / 60)}s \n`
    : "";

The value from the json is displayed in milliseconds, so to end up with seconds, divide by 1000 instead

**Comment by 403-html** [comment]
Great catch - how I could miss that...

**Comment by 403-html** [comment]
Resolved: package updated also on npm, update package to `0.2.2` if needed :)
Thank you for your report.
